name: barber
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.7
  connectivity_plus: ^6.1.4
  equatable: ^2.0.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^15.1.2
  http: ^1.4.0
  intl: 0.19.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockito: ^5.4.6
  build_runner: ^2.4.15
  integration_test:
    sdk: flutter
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
