// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5iLBQIwhlRyB8b6s9Tau3WyHZeWiv9SA',
    appId: '1:652849047731:web:4ba8ca8b887e4f02d3a8c6',
    messagingSenderId: '652849047731',
    projectId: 'barber-492fa',
    authDomain: 'barber-492fa.firebaseapp.com',
    storageBucket: 'barber-492fa.firebasestorage.app',
    measurementId: 'G-KWWY0RRSS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAemCJY6_3HiUmFwGATtnL-VO4974GpB5g',
    appId: '1:652849047731:android:e0ed8907ce544ccbd3a8c6',
    messagingSenderId: '652849047731',
    projectId: 'barber-492fa',
    storageBucket: 'barber-492fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI2wW1bAL4A3tGR8U6o2j_7ea86UTbuoM',
    appId: '1:652849047731:ios:f0ce45d20440ec11d3a8c6',
    messagingSenderId: '652849047731',
    projectId: 'barber-492fa',
    storageBucket: 'barber-492fa.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI2wW1bAL4A3tGR8U6o2j_7ea86UTbuoM',
    appId: '1:652849047731:ios:f0ce45d20440ec11d3a8c6',
    messagingSenderId: '652849047731',
    projectId: 'barber-492fa',
    storageBucket: 'barber-492fa.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5iLBQIwhlRyB8b6s9Tau3WyHZeWiv9SA',
    appId: '1:652849047731:web:28f8efe009c61687d3a8c6',
    messagingSenderId: '652849047731',
    projectId: 'barber-492fa',
    authDomain: 'barber-492fa.firebaseapp.com',
    storageBucket: 'barber-492fa.firebasestorage.app',
    measurementId: 'G-ENP2VKSX5B',
  );

}